name: Update Node.js Versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run every two hours
    - cron:  '0 0/2 * * *'
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x, 19.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: node -p "JSON.stringify(process.versions)" > ${{ matrix.node-version }}.json
    - uses: actions/upload-artifact@v3
      with:
        name: deps-${{ matrix.node-version }}
        path: ${{ matrix.node-version }}.json

  merge:
    runs-on: ubuntu-latest
    needs: [collect]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v3
        with:
          node-version: 17.x
      - uses: actions/download-artifact@v3
        with:
          path: collected-json
      - run: yarn install
      - run: find ./collected-json -name '*.json' | xargs yarn merge index.json
      - run: cat index.json
      - run: |
          if [ "$(git status --porcelain)" = "" ]; then
            echo "No new data, nothing to commit";
            exit;
          else
            echo "Git contents change, needs new commit"
            git config user.email baparham@gmail.com
            git config user.name Brad Parham
            git add index.json
            git commit -m "Update dependency data"
            git push
          fi
