name: Update Node.js Versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  collect:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.9.0, 16.9.1, 16.13.0, 16.13.1, 16.13.2, 16.x, 17.0.0, 17.0.1, 17.1.0, 17.2.0, 17.3.0, 17.3.1, 17.4.0, 17.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: node -p "JSON.stringify(process.versions)" > ${{ matrix.node-version }}.json
    - uses: actions/upload-artifact@v2
      with:
        name: deps-${{ matrix.node-version }}
        path: ${{ matrix.node-version }}.json

  merge:
    runs-on: ubuntu-latest
    needs: [collect]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
      - uses: actions/download-artifact@v2
        with:
          path: collected-json
      - run: yarn install
      - run: find ./collected-json -name '*.json' | xargs yarn merge dep-data.json
      - run: cat dep-data.json
      - run: |
          if [ "$(git status --porcelain)" = "" ]; then
            echo "No new data, nothing to commit";
            exit;
          else
            echo "Git contents change, needs new commit"
            git config user.email baparham@gmail.com
            git config user.name Brad Parham
            git add dep-data.json
            git commit -m "Update dependency data"
            git push
          fi
